version: '2'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=bankapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
